'use client';
import { useState, useEffect } from 'react';
import RecentVisitsPager from '@/app/components/RecentVisitsPager';
import AnalyticsDashboard from '@/app/components/AnalyticsDashboard';
import { classifyVisit } from '@/app/lib/visit-classification';
export default function ListPage() {
  const [items,setItems]=useState([]),[searchTerm,setSearchTerm]=useState(''),[pageSize,setPageSize]=useState(50),[currentPage,setCurrentPage]=useState(1),[loading,setLoading]=useState(true),[error,setError]=useState(''),[lastUpdated,setLastUpdated]=useState(null),[updatingId,setUpdatingId]=useState(null);
  const [sortColumn,setSortColumn]=useState(null),[sortDirection,setSortDirection]=useState('asc'),[showColumnSelector,setShowColumnSelector]=useState(false),[visibleColumns,setVisibleColumns]=useState(['shortCode','originalUrl','created','visibility','accesses','actions']); const CACHE_KEY='urlShortenerCache',CACHE_TTL_MS=5*60*1000;
  const allColumns=[{key:'shortCode',label:'Short Code'},{key:'shortenedUrl',label:'Shortened URL'},{key:'originalUrl',label:'Original URL'},{key:'title',label:'Title'},{key:'created',label:'Created'},{key:'visibility',label:'Visibility'},{key:'accesses',label:'Accesses'},{key:'expires',label:'Expires At'},{key:'maxClicks',label:'Max Clicks'},{key:'decay',label:'Type'},{key:'actions',label:'Actions'}];
  const normalize=value=>(value||[]).map(item=>({...item,stats:(item.stats||[]).map(stat=>({...stat,is_bot:classifyVisit(stat)}))}));
  const fetchUrls=async(force=false)=>{setLoading(true);setError('');try{if(!force){const c=JSON.parse(localStorage.getItem(CACHE_KEY)||'null');if(c&&Date.now()-c.timestamp<CACHE_TTL_MS){setItems(normalize(c.items));setLastUpdated(new Date(c.timestamp));setLoading(false);return;}}const r=await fetch('/api/urls'),d=await r.json();if(!r.ok){if(r.status===401||r.status===403)window.location.href='/login';setError(d.error||'Failed to load URLs');}else{const fetched=normalize(d.items);setItems(fetched);const now=new Date();setLastUpdated(now);localStorage.setItem(CACHE_KEY,JSON.stringify({timestamp:now.getTime(),items:fetched}));}}catch(e){setError('Failed to fetch URLs. Is the server running?')}finally{setLoading(false)}}; useEffect(()=>{fetchUrls()},[]);
  const handleSort=k=>{setSortDirection(sortColumn===k&&sortDirection==='asc'?'desc':'asc');setSortColumn(k);setCurrentPage(1)}; const toggleColumn=k=>setVisibleColumns(p=>p.includes(k)?(p.length===1?p:p.filter(x=>x!==k)):[...p,k]); let filtered=items.filter(i=>(i.original||'').toLowerCase().includes(searchTerm.toLowerCase())||(i.title||'').toLowerCase().includes(searchTerm.toLowerCase())); if(sortColumn)filtered=[...filtered].sort((a,b)=>{const v=i=>({shortCode:i.id,shortenedUrl:i.shortUrl,originalUrl:i.original,title:i.title||'',created:i.created?new Date(i.created).getTime():0,visibility:i.private?1:0,accesses:(i.stats||[]).filter(s=>!classifyVisit(s)).length,expires:i.expiresAt?new Date(i.expiresAt).getTime():0,maxClicks:i.maxClicks==null?0:Number(i.maxClicks),decay:i.decay?1:0}[sortColumn]??'');const x=v(a),y=v(b);return x<y?(sortDirection==='asc'?-1:1):x>y?(sortDirection==='asc'?1:-1):0}); const total=filtered.length,totalPages=Math.max(1,Math.ceil(total/pageSize)); useEffect(()=>{if(currentPage>totalPages)setCurrentPage(totalPages)},[currentPage,totalPages]); const pageItems=filtered.slice((currentPage-1)*pageSize,currentPage*pageSize); const go=p=>setCurrentPage(Math.max(1,Math.min(p,totalPages)));
  const toggle=async item=>{setUpdatingId(item.id);try{const r=await fetch(`/api/urls/${item.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({private:!item.private})});const d=await r.json();if(!r.ok)setError(d.error||'Failed to update visibility');else setItems(p=>p.map(i=>i.id===item.id?{...i,private:d.private}:i));}catch{setError('Failed to update visibility.')}finally{setUpdatingId(null)}};
  const cell=(i,k)=>{const s=i.stats||[],h=s.filter(x=>!classifyVisit(x)).length,b=s.filter(x=>classifyVisit(x)).length;switch(k){case'shortCode':return <code className="short-url">{i.id}</code>;case'shortenedUrl':return <a href={i.shortUrl} target="_blank" rel="noopener noreferrer" className="short-url">{i.shortUrl}</a>;case'originalUrl':return <a href={i.original} target="_blank" rel="noopener noreferrer" style={{wordBreak:'break-all'}}>{i.original}</a>;case'title':return i.title||<span className="metadata">(no title)</span>;case'created':return new Date(i.created).toLocaleString();case'visibility':return i.private?'Private':'Public';case'accesses':return `${h} (${b})`;case'expires':return i.expiresAt?new Date(i.expiresAt).toLocaleString():'(none)';case'maxClicks':return i.maxClicks!=null?`${s.length} / ${i.maxClicks}`:'(none)';case'decay':return i.decay?'🔥 Decay':'Standard';case'actions':return <div className="action-btns"><a href={`/stats/${i.id}`} className="action-btn" title="View Statistics">📊</a><button onClick={()=>toggle(i)} disabled={updatingId===i.id} className="action-btn" title={i.private?'Make Public':'Make Private'}>{i.private?'🔒':'🔓'}</button></div>;default:return null}};
  return <><div className="list-heading"><h2>All Shortened URLs</h2><button onClick={()=>setShowColumnSelector(!showColumnSelector)} className="secondary">Select Columns</button></div><p>Accesses are shown as human (bot), with legacy records classified by the shared visit rules.</p><div className="list-toolbar"><input placeholder="Search original URLs or titles..." value={searchTerm} onChange={e=>{setSearchTerm(e.target.value);setCurrentPage(1)}}/><select value={pageSize} onChange={e=>{setPageSize(Number(e.target.value));setCurrentPage(1)}}><option value="10">10</option><option value="25">25</option><option value="50">50</option></select><button onClick={()=>fetchUrls(true)} disabled={loading} className="secondary">{loading?'Refreshing...':'Refresh List'}</button></div>{showColumnSelector&&<div className="column-selector">{allColumns.map(c=><label key={c.key}><input type="checkbox" checked={visibleColumns.includes(c.key)} onChange={()=>toggleColumn(c.key)}/> {c.label}</label>)}</div>}{error&&<div className="error">{error}</div>}{loading&&<p className="metadata">Loading...</p>}{!loading&&!!pageItems.length&&<><div className="metadata">Showing {(currentPage-1)*pageSize+1}–{Math.min(currentPage*pageSize,total)} of {total}</div><table><thead><tr>{allColumns.filter(c=>visibleColumns.includes(c.key)).map(c=><th key={c.key} onClick={()=>c.key!=='actions'&&handleSort(c.key)}>{c.label}{sortColumn===c.key?(sortDirection==='asc'?' ▲':' ▼'):''}</th>)}</tr></thead><tbody>{pageItems.map(i=><tr key={i.id}>{allColumns.filter(c=>visibleColumns.includes(c.key)).map(c=><td key={c.key}>{cell(i,c.key)}</td>)}</tr>)}</tbody></table><PageControls page={currentPage} totalPages={totalPages} onPageChange={go}/></>}{!loading&&!pageItems.length&&<p className="metadata">No matching URLs.</p>}{lastUpdated&&<p className="metadata">Cached at {lastUpdated.toLocaleTimeString()}</p>}<RecentVisitsPager/><AnalyticsDashboard/></>;
}
function PageControls({page,totalPages,onPageChange}){return <nav className="page-navigator"><button className="secondary" onClick={()=>onPageChange(1)} disabled={page===1}>« First</button><button className="secondary" onClick={()=>onPageChange(page-1)} disabled={page===1}>‹ Previous</button><span className="metadata">Page {page} of {totalPages}</span><button className="secondary" onClick={()=>onPageChange(page+1)} disabled={page===totalPages}>Next ›</button><button className="secondary" onClick={()=>onPageChange(totalPages)} disabled={page===totalPages}>Last »</button></nav>}
