'use client';

import { useState, useEffect } from 'react';

export default function ListPage() {
  const [items, setItems] = useState([]); const [searchTerm, setSearchTerm] = useState(''); const [pageSize, setPageSize] = useState(50); const [currentPage, setCurrentPage] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [lastUpdated, setLastUpdated] = useState(null); const [updatingId, setUpdatingId] = useState(null);
  const [sortColumn, setSortColumn] = useState(null); const [sortDirection, setSortDirection] = useState('asc'); const [showColumnSelector, setShowColumnSelector] = useState(false); const [visibleColumns, setVisibleColumns] = useState(['shortCode','originalUrl','created','visibility','accesses','actions']);
  const CACHE_KEY='urlShortenerCache'; const CACHE_TTL_MS=5*60*1000;
  const allColumns=[{key:'shortCode',label:'Short Code'},{key:'shortenedUrl',label:'Shortened URL'},{key:'originalUrl',label:'Original URL'},{key:'title',label:'Title'},{key:'created',label:'Created'},{key:'visibility',label:'Visibility'},{key:'accesses',label:'Accesses'},{key:'expires',label:'Expires At'},{key:'maxClicks',label:'Max Clicks'},{key:'decay',label:'Type'},{key:'actions',label:'Actions'}];
  const normalizedItems = value => (value || []).map(item => ({ ...item, stats:(item.stats||[]).map(stat => ({...stat,is_bot:stat.is_bot===true || stat.isBot===true})) }));
  const fetchUrls=async(forceRefresh=false)=>{setLoading(true);setError('');try{if(!forceRefresh){const cachedStr=localStorage.getItem(CACHE_KEY);if(cachedStr){const cached=JSON.parse(cachedStr);if(Date.now()-cached.timestamp<CACHE_TTL_MS){setItems(normalizedItems(cached.items));setLastUpdated(new Date(cached.timestamp));setLoading(false);return;}}}const response=await fetch('/api/urls');const data=await response.json();if(!response.ok){if(response.status===401||response.status===403){window.location.href='/login';return;}setError(data.error||'Failed to load URLs');}else{const fetchedItems=normalizedItems(data.items);setItems(fetchedItems);const now=new Date();setLastUpdated(now);localStorage.setItem(CACHE_KEY,JSON.stringify({timestamp:now.getTime(),items:fetchedItems}));}}catch(e){setError('Failed to fetch URLs. Is the server running?')}finally{setLoading(false)}};
  useEffect(()=>{fetchUrls();},[]);
  const handleSort=key=>{setSortDirection(sortColumn===key&&sortDirection==='asc'?'desc':'asc');setSortColumn(key);setCurrentPage(1)}; const indicator=key=>sortColumn===key?(sortDirection==='asc'?' ▲':' ▼'):'';
  const toggleColumn=key=>setVisibleColumns(prev=>prev.includes(key)?(prev.length===1?prev:prev.filter(k=>k!==key)):[...prev,key]);
  let filteredItems=items.filter(item=>(item.original||'').toLowerCase().includes(searchTerm.toLowerCase())||(item.title||'').toLowerCase().includes(searchTerm.toLowerCase()));
  if(sortColumn) filteredItems=[...filteredItems].sort((a,b)=>{const value=item=>{switch(sortColumn){case'shortCode':return item.id||'';case'shortenedUrl':return item.shortUrl||'';case'originalUrl':return item.original||'';case'title':return item.title||'';case'created':return item.created?new Date(item.created).getTime():0;case'visibility':return item.private?1:0;case'accesses':return (item.stats||[]).filter(s=>s.is_bot!==true).length;case'expires':return item.expiresAt?new Date(item.expiresAt).getTime():0;case'maxClicks':return item.maxClicks==null?0:Number(item.maxClicks);case'decay':return item.decay?1:0;default:return''}};const x=value(a),y=value(b);return x<y?(sortDirection==='asc'?-1:1):x>y?(sortDirection==='asc'?1:-1):0});
  const totalItems=filteredItems.length,totalPages=Math.max(1,Math.ceil(totalItems/pageSize)); useEffect(()=>{if(currentPage>totalPages)setCurrentPage(totalPages)},[currentPage,totalPages]); const paginatedItems=filteredItems.slice((currentPage-1)*pageSize,currentPage*pageSize); const goToPage=p=>setCurrentPage(Math.max(1,Math.min(p,totalPages)));
  const handleToggleVisibility=async item=>{setUpdatingId(item.id);try{const r=await fetch(`/api/urls/${item.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({private:!item.private})});const d=await r.json();if(!r.ok){if(r.status===401||r.status===403)window.location.href='/login';else setError(d.error||'Failed to update visibility')}else setItems(prev=>prev.map(i=>i.id===item.id?{...i,private:d.private}:i))}catch(e){setError('Failed to update visibility. Is the server running?')}finally{setUpdatingId(null)}};
  const StatsIcon=()=> <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M3 3v18h18M18 17V9M13 17V5M8 17v-3"/></svg>; const PrivacyIcon=({isPrivate})=><span aria-hidden="true">{isPrivate?'🔒':'🔓'}</span>;
  const renderCell=(item,key)=>{const stats=item.stats||[],humans=stats.filter(s=>s.is_bot!==true).length,bots=stats.filter(s=>s.is_bot===true).length;switch(key){case'shortCode':return <code className="short-url">{item.id}</code>;case'shortenedUrl':return <a href={item.shortUrl} target="_blank" rel="noopener noreferrer" className="short-url">{item.shortUrl}</a>;case'originalUrl':return <a href={item.original} target="_blank" rel="noopener noreferrer" style={{wordBreak:'break-all'}}>{item.original}</a>;case'title':return item.title||<span className="metadata">(no title)</span>;case'created':return <span className="metadata">{new Date(item.created).toLocaleString()}</span>;case'visibility':return item.private?'Private':'Public';case'accesses':return <span className="metadata">{humans} ({bots})</span>;case'expires':return item.expiresAt?new Date(item.expiresAt).toLocaleString():'(none)';case'maxClicks':return item.maxClicks!=null?`${stats.length} / ${item.maxClicks}`:'(none)';case'decay':return item.decay?'🔥 Decay':'Standard';case'actions':return <div className="action-btns"><a href={`/stats/${item.id}`} className="action-btn" title="View Statistics"><StatsIcon/></a><button onClick={()=>handleToggleVisibility(item)} disabled={updatingId===item.id} className="action-btn secondary" title={item.private?'Make Public':'Make Private'}><PrivacyIcon isPrivate={item.private}/></button></div>;default:return null}};
  return <><div className="list-heading"><h2>All Shortened URLs</h2><button onClick={()=>setShowColumnSelector(!showColumnSelector)} className="secondary">Select Columns</button></div>{showColumnSelector&&<div className="column-selector">{allColumns.map(c=><label key={c.key}><input type="checkbox" checked={visibleColumns.includes(c.key)} onChange={()=>toggleColumn(c.key)}/> {c.label}</label>)}</div>}<p>Below is a list of all URLs that have been shortened. Accesses are shown as human (bot), with legacy records treated as human.</p><div className="list-toolbar"><input type="text" placeholder="Search original URLs or titles..." value={searchTerm} onChange={e=>{setSearchTerm(e.target.value);setCurrentPage(1)}}/><select value={pageSize} onChange={e=>{setPageSize(Number(e.target.value));setCurrentPage(1)}}><option value="10">10</option><option value="25">25</option><option value="50">50</option></select><button onClick={()=>fetchUrls(true)} disabled={loading} className="secondary">{loading?'Refreshing...':'Refresh List'}</button></div>{error&&<div className="error">{error}</div>}{loading&&<p className="metadata">Loading...</p>}{!loading&&!paginatedItems.length&&<p className="metadata">No matching URLs.</p>}{!loading&&!!paginatedItems.length&&<><div className="metadata">Showing {(currentPage-1)*pageSize+1}–{Math.min(currentPage*pageSize,totalItems)} of {totalItems}</div><table><thead><tr>{allColumns.filter(c=>visibleColumns.includes(c.key)).map(c=><th key={c.key} onClick={()=>c.key!=='actions'&&handleSort(c.key)}>{c.label}{indicator(c.key)}</th>)}</tr></thead><tbody>{paginatedItems.map(item=><tr key={item.id}>{allColumns.filter(c=>visibleColumns.includes(c.key)).map(c=><td key={c.key}>{renderCell(item,c.key)}</td>)}</tr>)}</tbody></table><PageControls page={currentPage} totalPages={totalPages} onPageChange={goToPage}/></>}{lastUpdated&&<p className="metadata">Cached at {lastUpdated.toLocaleTimeString()}</p>}</>;
}
function PageControls({page,totalPages,onPageChange}){return <nav className="page-navigator" aria-label="URL list page navigation"><button className="secondary" onClick={()=>onPageChange(1)} disabled={page===1}>« First</button><button className="secondary" onClick={()=>onPageChange(page-1)} disabled={page===1}>‹ Previous</button><span className="metadata">Page {page} of {totalPages}</span><button className="secondary" onClick={()=>onPageChange(page+1)} disabled={page===totalPages}>Next ›</button><button className="secondary" onClick={()=>onPageChange(totalPages)} disabled={page===totalPages}>Last »</button></nav>}
