'use client';
import { useState, useEffect } from 'react';
import RecentVisitsPager from '@/app/components/RecentVisitsPager';
import AnalyticsDashboard from '@/app/components/AnalyticsDashboard';
import { classifyVisit } from '@/app/lib/visit-classification';

function SocialIcon({ name }) {
  const paths = {
    linkedin: <><path d="M6 6.5A1.5 1.5 0 1 0 6 3.5a1.5 1.5 0 0 0 0 3Z"/><path d="M4.8 8.2v8h2.4v-8H4.8Zm4 0v8h2.4v-4.1c0-1.1.2-2.2 1.6-2.2 1.4 0 1.4 1.3 1.4 2.3v4h2.4v-4.5c0-2.2-.5-3.9-3.1-3.9-1.2 0-2 .7-2.4 1.2h-.1V8.2H8.8Z"/></>,
    mastodon: <path d="M16.8 7.1c0-2.8-1.8-3.6-1.8-3.6C14.1 3 12.6 2.7 10.5 2.7h-.1c-2.1 0-3.6.3-4.5.8 0 0-1.8.8-1.8 3.6 0 .7 0 1.6.1 2.5.2 3 1.2 6 4.5 6.7 1.1.2 2.1.3 3.1.2 1.8-.1 2.8-.6 2.8-.6l-.1-1.5s-1.3.4-2.7.5c-1.4.1-2.9-.1-3.1-1.6a3.4 3.4 0 0 1 0-.5c1.9.5 3.5.6 5.2.3 1.7-.3 3.2-1 3.2-4.1V7.1ZM14 11.2h-1.8V7.3c0-.8-.3-1.2-1-1.2-.8 0-1.2.5-1.2 1.5v2.1H8.2V7.6c0-1-.4-1.5-1.2-1.5-.7 0-1 .4-1 1.2v3.9H4.2V7.2c0-.8.2-1.5.7-2 .5-.5 1.1-.8 1.9-.8 1 0 1.7.4 2.1 1.1l.5.8.5-.8c.4-.7 1.1-1.1 2.1-1.1.8 0 1.4.3 1.9.8.5.5.7 1.2.7 2v4Z"/>,
    x: <path d="M4 3.5h3.2l3.1 4.1 3.6-4.1h2.1l-4.7 5.4 4.7 6.3h-3.2l-3.3-4.4-3.9 4.4H3.5l5.1-5.8L4 3.5Zm2.1 1.6 6.3 8.5h.9L7 5.1h-.9Z"/>,
    notes: <><path d="M5 3.5h8.3L16.5 6v10.5H5V3.5Z"/><path d="M13.3 3.7V6h2.4M7.5 8.5h6.5M7.5 11h6.5M7.5 13.5h4"/></>,
    substack: <><path d="M3.5 4h13v2.2h-13zM3.5 7.4h13v2.2h-13zM3.5 10.8h13V13h-13z"/><path d="M6.2 14.8h7.6v1.7H6.2z"/></>
  };
  return <svg viewBox="0 0 20 20" aria-hidden="true" focusable="false">{paths[name]}</svg>;
}

const SOCIAL_NETWORKS = [
  { key: 'linkedin', label: 'LinkedIn' }, { key: 'mastodon', label: 'Mastodon' },
  { key: 'x', label: 'X' }, { key: 'notes', label: 'Notes' }, { key: 'substack', label: 'Substack' }
];

export default function ListPage() {
  const [items,setItems]=useState([]),[searchTerm,setSearchTerm]=useState(''),[pageSize,setPageSize]=useState(10),[currentPage,setCurrentPage]=useState(1),[loading,setLoading]=useState(true),[error,setError]=useState(''),[lastUpdated,setLastUpdated]=useState(null),[updatingId,setUpdatingId]=useState(null),[shareItem,setShareItem]=useState(null),[copiedSource,setCopiedSource]=useState('');
  const [sortColumn,setSortColumn]=useState(null),[sortDirection,setSortDirection]=useState('asc'),[showColumnSelector,setShowColumnSelector]=useState(false),[visibleColumns,setVisibleColumns]=useState(['shortCode','originalUrl','created','visibility','accesses','actions']);
  const CACHE_KEY='urlShortenerCache',CACHE_TTL_MS=5*60*1000;
  const allColumns=[{key:'shortCode',label:'Short Code'},{key:'shortenedUrl',label:'Shortened URL'},{key:'originalUrl',label:'Original URL'},{key:'title',label:'Title'},{key:'created',label:'Created'},{key:'visibility',label:'Visibility'},{key:'accesses',label:'Accesses'},{key:'expires',label:'Expires At'},{key:'maxClicks',label:'Max Clicks'},{key:'decay',label:'Type'},{key:'actions',label:'Actions'}];
  const normalize=value=>(value||[]).map(item=>({...item,stats:(item.stats||[]).map(stat=>({...stat,is_bot:classifyVisit(stat)}))}));
  const fetchUrls=async(force=false)=>{setLoading(true);setError('');try{if(!force){const c=JSON.parse(localStorage.getItem(CACHE_KEY)||'null');if(c&&Date.now()-c.timestamp<CACHE_TTL_MS){setItems(normalize(c.items));setLastUpdated(new Date(c.timestamp));setLoading(false);return;}}const r=await fetch('/api/urls'),d=await r.json();if(!r.ok){if(r.status===401||r.status===403)window.location.href='/login';setError(d.error||'Failed to load URLs');}else{const fetched=normalize(d.items);setItems(fetched);const now=new Date();setLastUpdated(now);localStorage.setItem(CACHE_KEY,JSON.stringify({timestamp:now.getTime(),items:fetched}));}}catch(e){setError('Failed to fetch URLs. Is the server running?')}finally{setLoading(false)}};
  useEffect(()=>{fetchUrls()},[]);
  useEffect(()=>{const close=e=>e.key==='Escape'&&setShareItem(null);document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close)},[]);
  const handleSort=k=>{setSortDirection(sortColumn===k&&sortDirection==='asc'?'desc':'asc');setSortColumn(k);setCurrentPage(1)};
  const toggleColumn=k=>setVisibleColumns(p=>p.includes(k)?(p.length===1?p:p.filter(x=>x!==k)):[...p,k]);
  let filtered=items.filter(i=>(i.original||'').toLowerCase().includes(searchTerm.toLowerCase())||(i.title||'').toLowerCase().includes(searchTerm.toLowerCase()));
  if(sortColumn)filtered=[...filtered].sort((a,b)=>{const v=i=>({shortCode:i.id,shortenedUrl:i.shortUrl,originalUrl:i.original,title:i.title||'',created:i.created?new Date(i.created).getTime():0,visibility:i.private?1:0,accesses:(i.stats||[]).filter(s=>!classifyVisit(s)).length,expires:i.expiresAt?new Date(i.expiresAt).getTime():0,maxClicks:i.maxClicks==null?0:Number(i.maxClicks),decay:i.decay?1:0}[sortColumn]??'');const x=v(a),y=v(b);return x<y?(sortDirection==='asc'?-1:1):x>y?(sortDirection==='asc'?1:-1):0});
  const total=filtered.length,totalPages=Math.max(1,Math.ceil(total/pageSize)); useEffect(()=>{if(currentPage>totalPages)setCurrentPage(totalPages)},[currentPage,totalPages]); const pageItems=filtered.slice((currentPage-1)*pageSize,currentPage*pageSize); const go=p=>setCurrentPage(Math.max(1,Math.min(p,totalPages)));
  const toggle=async item=>{setUpdatingId(item.id);try{const r=await fetch(`/api/urls/${item.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({private:!item.private})});const d=await r.json();if(!r.ok)setError(d.error||'Failed to update visibility');else setItems(p=>p.map(i=>i.id===item.id?{...i,private:d.private}:i));}catch{setError('Failed to update visibility.')}finally{setUpdatingId(null)}};
  const shareUrl=(item,source)=>{const url=new URL(item.shortUrl,window.location.origin);url.searchParams.set('source',source);return url.toString()};
  const copyUrl=async(url,source)=>{try{await navigator.clipboard.writeText(url);setCopiedSource(source);setTimeout(()=>setCopiedSource(''),1800)}catch{setError('Unable to copy this link.')}};
  const cell=(i,k)=>{const s=i.stats||[],h=s.filter(x=>!classifyVisit(x)).length,b=s.filter(x=>classifyVisit(x)).length;switch(k){case'shortCode':return <code className="short-url">{i.id}</code>;case'shortenedUrl':return <a href={i.shortUrl} target="_blank" rel="noopener noreferrer" className="short-url">{i.shortUrl}</a>;case'originalUrl':return <a href={i.original} target="_blank" rel="noopener noreferrer" style={{wordBreak:'break-all'}}>{i.original}</a>;case'title':return i.title||<span className="metadata">(no title)</span>;case'created':return new Date(i.created).toLocaleString();case'visibility':return i.private?'Private':'Public';case'accesses':return `${h} (${b})`;case'expires':return i.expiresAt?new Date(i.expiresAt).toLocaleString():'(none)';case'maxClicks':return i.maxClicks!=null?`${s.length} / ${i.maxClicks}`:'(none)';case'decay':return i.decay?'🔥 Decay':'Standard';case'actions':return <div className="action-btns"><a href={`/stats/${i.id}`} className="action-btn" title="View Statistics" aria-label="View Statistics">📊</a><button onClick={()=>toggle(i)} disabled={updatingId===i.id} className="action-btn" title={i.private?'Make Public':'Make Private'} aria-label={i.private?'Make Public':'Make Private'}>{i.private?'🔒':'🔓'}</button><button onClick={()=>setShareItem(i)} className="action-btn share-action" title="Share shortened URL" aria-label="Share shortened URL"><span aria-hidden="true">↗</span></button></div>;default:return null}};
  const share=async(item,source)=>{const url=shareUrl(item,source),encoded=encodeURIComponent(url);if(source==='linkedin'){window.open(`https://www.linkedin.com/sharing/share-offsite/?url=${encoded}`,'_blank','noopener,noreferrer');return;}if(source==='x'){window.open(`https://x.com/intent/post?url=${encoded}`,'_blank','noopener,noreferrer');return;}if(source==='substack'){window.open(`https://substack.com/share?url=${encoded}`,'_blank','noopener,noreferrer');return;}if(navigator.share){try{await navigator.share({title:item.title||'Shortened link',url});return;}catch(e){if(e.name==='AbortError')return;}}await copyUrl(url,source)};
  return <><div className="list-heading"><h2>All Shortened URLs</h2><button onClick={()=>setShowColumnSelector(!showColumnSelector)} className="secondary">Select Columns</button></div><p>Accesses are shown as human (bot), with legacy records classified by the shared visit rules.</p><div className="list-toolbar"><input placeholder="Search original URLs or titles..." value={searchTerm} onChange={e=>{setSearchTerm(e.target.value);setCurrentPage(1)}}/><select value={pageSize} onChange={e=>{setPageSize(Number(e.target.value));setCurrentPage(1)}}><option value="10">10</option><option value="25">25</option><option value="50">50</option></select><button onClick={()=>fetchUrls(true)} disabled={loading} className="secondary">{loading?'Refreshing...':'Refresh List'}</button></div>{showColumnSelector&&<div className="column-selector">{allColumns.map(c=><label key={c.key}><input type="checkbox" checked={visibleColumns.includes(c.key)} onChange={()=>toggleColumn(c.key)}/> {c.label}</label>)}</div>}{error&&<div className="error">{error}</div>}{loading&&<p className="metadata">Loading...</p>}{!loading&&!!pageItems.length&&<><div className="metadata">Showing {(currentPage-1)*pageSize+1}–{Math.min(currentPage*pageSize,total)} of {total}</div><table><thead><tr>{allColumns.filter(c=>visibleColumns.includes(c.key)).map(c=><th key={c.key} onClick={()=>c.key!=='actions'&&handleSort(c.key)}>{c.label}{sortColumn===c.key?(sortDirection==='asc'?' ▲':' ▼'):''}</th>)}</tr></thead><tbody>{pageItems.map(i=><tr key={i.id}>{allColumns.filter(c=>visibleColumns.includes(c.key)).map(c=><td key={c.key}>{cell(i,c.key)}</td>)}</tr>)}</tbody></table><PageControls page={currentPage} totalPages={totalPages} onPageChange={go}/></>}{!loading&&!pageItems.length&&<p className="metadata">No matching URLs.</p>}{lastUpdated&&<p className="metadata">Cached at {lastUpdated.toLocaleTimeString()}</p>}<RecentVisitsPager/><AnalyticsDashboard/>{shareItem&&<div className="share-modal-backdrop" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&setShareItem(null)}><section className="share-modal" role="dialog" aria-modal="true" aria-labelledby="share-title"><div className="share-modal-header"><h3 id="share-title">Share shortened URL</h3><button className="share-close" onClick={()=>setShareItem(null)} aria-label="Close sharing dialog">×</button></div><p className="metadata">Choose a network to prepare a tagged link. Copy is the only available action.</p><div className="share-network-list">{SOCIAL_NETWORKS.map(network=>{const url=shareUrl(shareItem,network.key);return <div className="share-network-row" key={network.key}><div className="share-network-label"><SocialIcon name={network.key}/><span>{network.label}</span></div><a className="share-tagged-url" href={url} target="_blank" rel="noopener noreferrer">{url}</a><button className="share-copy" onClick={()=>copyUrl(url,network.key)}>{copiedSource===network.key?'Copied':'Copy'}</button></div>})}</div></section></div>}</>;
}
function PageControls({page,totalPages,onPageChange}){return <nav className="page-navigator"><button className="secondary" onClick={()=>onPageChange(1)} disabled={page===1}>« First</button><button className="secondary" onClick={()=>onPageChange(page-1)} disabled={page===1}>‹ Previous</button><span className="metadata">Page {page} of {totalPages}</span><button className="secondary" onClick={()=>onPageChange(page+1)} disabled={page===totalPages}>Next ›</button><button className="secondary" onClick={()=>onPageChange(totalPages)} disabled={page===totalPages}>Last »</button></nav>}
