import { NextResponse } from 'next/server';
import { headers } from 'next/headers';
import { findUrlByShort, logAccess, isUrlExpired, isBotUserAgent } from '@/app/lib/urls';

const DECAY_PROTECTION_BOTS = [
  'WhatsApp', 'Telegram', 'Slack', 'Discord', 'facebookexternalhit',
  'Twitterbot', 'LinkedInBot', 'SkypeUriPreview', 'Googlebot', 'bingbot',
  'Slackbot', 'Facebot', 'ia_archiver', 'crawler', 'bot',
];
function isDecayProtectionBot(userAgent) { if (!userAgent) return false; const ua=userAgent.toLowerCase(); return DECAY_PROTECTION_BOTS.some(pattern=>ua.includes(pattern.toLowerCase())); }
function renderBurnedPage(short, entry=null) { const html=`<!DOCTYPE html><html><head><meta charset="utf-8"><title>Confidential Link Destroyed</title><style>body{font-family:system-ui,Arial,sans-serif;background:#fff;color:#151515;margin:0;padding:40px 20px;line-height:1.5}.container{max-width:620px;margin:0 auto;background:#f9f9f9;border:1px solid #e5e5e5;padding:32px;border-radius:4px}h1{font-family:Georgia,serif;font-size:28px;margin:0 0 16px;color:#991b1b}.status{background:#fef2f2;border:1px solid #fecaca;color:#991b1b;padding:12px 16px;margin:16px 0;font-size:15px}.meta{font-size:13px;color:#666;margin-top:16px}a{color:#66cd7a;text-decoration:none}.flame{font-size:32px;margin-bottom:8px;display:block}</style></head><body><div class="container"><span class="flame">🔥</span><h1>Confidential Link Destroyed</h1><div class="status">This link was configured to self-destruct after its first view and is no longer available.</div><p>The original destination can no longer be reached via this short URL. The link record is retained for internal statistics only.</p><div class="meta">Short code: <code>${short}</code><br>${entry?.created?`Originally created: ${new Date(entry.created).toLocaleString()}<br>`:''}This was a single-use (Decay / Burn After Reading) link.</div><p style="margin-top:24px"><a href="/">Return to URL Shortener</a></p></div></body></html>`; return new NextResponse(html,{status:410,headers:{'Content-Type':'text/html; charset=utf-8'}}); }
function renderExpiredPage(entry) { const html=`<!DOCTYPE html><html><head><meta charset="utf-8"><title>Link Expired</title><style>body{font-family:system-ui,Arial,sans-serif;padding:40px 20px;line-height:1.5}.container{max-width:620px;margin:auto;background:#f9f9f9;border:1px solid #e5e5e5;padding:32px}.status{background:#fef2f2;border:1px solid #fecaca;color:#991b1b;padding:12px 16px;margin:16px 0}a{color:#66cd7a}</style></head><body><div class="container"><h1>Link Expired</h1><div class="status">This shortened link has expired or reached its usage limit and is no longer active.</div><p>The original destination is no longer accessible via this short URL.</p><p>Short code: <code>${entry.id}</code><br>Created: ${new Date(entry.created).toLocaleString()}</p><p><a href="/">Return to URL Shortener</a></p></div></body></html>`; return new NextResponse(html,{status:410,headers:{'Content-Type':'text/html; charset=utf-8'}}); }
export async function GET(request,{params}) { try { const {short}=params; if(!short)return NextResponse.json({error:'Short code required'},{status:400}); const entry=await findUrlByShort(short); if(!entry?.original)return renderBurnedPage(short); if(isUrlExpired(entry))return renderExpiredPage(entry); const isDecay=!!entry.decay; if(isDecay&&(entry.stats||[]).length>0)return renderBurnedPage(short,entry); const requestHeaders=headers(); const userAgent=requestHeaders.get('user-agent')||''; const isBot=isBotUserAgent(userAgent); if(isDecay&&isDecayProtectionBot(userAgent))return NextResponse.redirect(entry.original,302); try { const ip=requestHeaders.get('x-forwarded-for')?.split(',')[0]?.trim()||requestHeaders.get('x-real-ip')||requestHeaders.get('cf-connecting-ip')||'unknown'; await logAccess(short,{timestamp:new Date().toISOString(),ip,userAgent,referer:requestHeaders.get('referer')||'',isBot}); } catch(error){console.error('Failed to log access stats:',error);} return NextResponse.redirect(entry.original,302); } catch(error){console.error('Redirect error:',error);return new NextResponse('Internal server error',{status:500});} }
